# Generated by Django 4.2.3 on 2023-09-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_allergen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('snacks', 'Snacks and Appetizers'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('glutenfree', 'Gluten-free'), ('dairyfree', 'Dairy-free'), ('keto', 'Keto'), ('paleo', 'Paleo')], default='snacks', max_length=30, unique=True),
        ),
    ]
