# Generated by Django 4.2.3 on 2023-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_recipe_allergen_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recipes',
            field=models.ManyToManyField(related_name='category', to='recipes.recipe'),
        ),
    ]
