# Generated by Django 4.2.3 on 2023-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_category_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recipes',
            field=models.ManyToManyField(related_name='categories', to='recipes.recipe'),
        ),
    ]
