# Generated by Django 4.2.3 on 2023-09-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_category_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(related_name='recipes', to='recipes.allergen'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.category'),
        ),
    ]
