# Generated by Django 4.2.3 on 2023-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_allergen_recipes_recipe_allergens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('drinks', 'Drinks'), ('snacks', 'Snacks and Appetizers'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('glutenfree', 'Gluten-free'), ('dairyfree', 'Dairy-free'), ('keto', 'Keto'), ('paleo', 'Paleo')], default='snacks', max_length=30),
        ),
    ]
