# Generated by Django 4.2.3 on 2023-09-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_allergen_recipes_remove_category_recipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.allergen'),
        ),
    ]
