# Generated by Django 4.2.3 on 2023-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_step',
            field=models.FloatField(default=0.1),
        ),
    ]
